### ISSUE TITLE
Publish how-to on adding support for Angular UI to a microservice

### ISSUE THREAD

**Issue by hugoqribeiro** [PrimaveraDeveloper/lithium#4]
The howto section has a topic that needs to be written on this matter.
Important as new microservices often are being implemented using Angular for the front-end.

**Comment by hugoqribeiro** [comment]
@PedroMGMendes?

**Comment by PedroMGMendes** [comment]
[How to add support for Angular user interface to a microservice](https://github.com/PrimaveraDeveloper/lithium/blob/master/howto/howto-add-user-interface-ngx.md).
This how to only details the required code(server) changes to support Angular Apps. 

An extended tutorial should be made detailing all steps but from a angular app point of view (creating something like a ToDo App from the ground up and accessing a lithium microservice API). 

Next, I'll create a guide somewhat similar to [How to upgrade a microservice from Lithium v1.0 to Lithium v2.0](https://github.com/PrimaveraDeveloper/lithium/blob/master/howto/howto-migration-to-lithium-2.0/README.md) but in regard to creating the angular client app from the ground up.
