### ISSUE TITLE
How-on on adding task box needs refactoring

### ISSUE THREAD

**Issue by hugoqribeiro** [PrimaveraDeveloper/lithium#5]
This how-to topic needs improvements:

- The text needs to adhere to the form used in other topics (you instead of we, more details in steps, etc.)
- The steps required need to be simplified (new features in Hydrogen?)
- The topic is not listed in README

**Comment by p-brito** [comment]
- [x] The text needs to adhere to the form used in other topics :

- [x]   you instead of we
- [x]   more details steps

- [x] The steps required need to be simplified (new features in Hydrogen?)
- [x] The topic is not listed in README

**Comment by hugoqribeiro** [comment]
@p-brito close the issue, if resolved.
