### ISSUE TITLE
Releases and packages tabs should be removed from the repository root page.

### ISSUE THREAD

**Issue by ibbgomes** [PrimaveraDeveloper/lithium#6]
Considering that:

1) This repository is for documentation purposes only;
2) There were no releases or created packages since the repository inception.

The respective tabs are irrelevant and therefore should be removed from the repository root page.

![tabs](https://user-images.githubusercontent.com/16123612/96110496-d9d05a00-0ed7-11eb-8e03-a9c21c9657ba.jpg)

**Comment by hugoqribeiro** [comment]
Hey! I have no clue on how to achieve that! :)

**Comment by Kiril1512** [comment]
> Hey! I have no clue on how to achieve that! :)

@hugoqribeiro on Lithium main page, click on "About" options like on the image:

[About](http://prntscr.com/vbu0bd)

Then remove the release and packages option:

[Remove Options](http://prntscr.com/vbu0v3)

Done!

**Comment by PrimaveraDeveloper** [comment]
Done @Kiril1512.
Would never have seen that icon.... :)
Thanks.

**Comment by Kiril1512** [comment]
@ibbgomes you can close the issue now ;)

**Comment by ibbgomes** [comment]
Thank you @hugoqribeiro and @Kiril1512.
